CREATE TABLE "inscritos" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "inscritos_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"nome" text NOT NULL,
	"cpf" text NOT NULL,
	"email" text NOT NULL,
	"mercado_pago_id" text,
	"payment_status" text DEFAULT 'pending',
	"email_sent" boolean DEFAULT false,
	"metadata" jsonb
);
